### ISSUE TITLE
Request: Add descriptions to the effects.

### ISSUE THREAD

**Issue by GorgoPrimus** [silvative/pf2e-exploration-effects#6]
The vast majority (all?) of effects in system have descriptions of what an effect is doing if you hover over it's icon next to chat in the top right, but these don't. Is it possible to get something so it'd be easier to remember for newer players? Right now they'd have to go back into chat (and possibly scroll up)and read the action in the chat every time.

**Comment by silvative** [comment]
The effects link to the action, which contains the rules for the related ability. None of the activities in this adventure except for Scout have an effect in the conventional sense- and that isn't automated, so it would be misleading to list one in the description.

![image](https://github.com/silvative/pf2e-exploration-effects/assets/66365038/4c412d1f-a330-4685-b7b3-018deca59224)
